services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: footballstats-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - footballstats-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: footballstats-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    depends_on:
      - backend
    networks:
      - footballstats-network

networks:
  footballstats-network:
    driver: bridge