server:
  port: 8080

spring:
  application:
    name: footballstats-backend
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.footballstats: INFO
    reactor.netty: INFO